spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/toy-project3?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: Asia/Seoul
  config:
    import: application-secret.yaml